name: smart_condo
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"







dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  http: ^1.1.0
  intl: ^0.17.0
  logger: ^2.5.0
  url_launcher: ^6.0.9
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  flutter_email_sender: ^7.0.0

  #STATE MANAGEMENT
  get: ^4.3.8
  get_storage: ^2.0.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  lottie: ^3.0.0
  connectivity_plus: ^6.1.3
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  modal_progress_hud_nsn: ^0.5.1
  firebase_app_check: ^0.3.2+5


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  
  





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

    - assets/images/on_boarding_screen/
    - assets/icons/
    - assets/logos/



  fonts:
    - family: Adobe 
      fonts:
        - asset: assets/fonts/AdobeArabic-Bold.otf
        - asset: assets/fonts/AdobeArabic-BoldItalic.otf
        - asset: assets/fonts/AdobeArabic-Italic.otf
          weight: 500
        - asset: assets/fonts/AdobeArabic-Regular.otf
        - asset: assets/fonts/arial.ttf
        - asset: assets/fonts/arial.ttf
          weight: 500
        - asset: assets/fonts/arialbi.ttf
        - asset: assets/fonts/ariali.ttf
        - asset: assets/fonts/ARIALN.ttf
          style: italic

        - asset: assets/fonts/ARIALNB.ttf
        - asset: assets/fonts/ARIALNBI.ttf
        - asset: assets/fonts/ARIALNI.ttf
        - asset: assets/fonts/ARIALUNI.ttf
        - asset: assets/fonts/ariblk.ttf
        - asset: assets/fonts/ARLRDBD.TTF
        - asset: assets/fonts/PTBLDDSK.TTF
        - asset: assets/fonts/STENCIL.TTF
        - asset: assets/fonts/StencilStd.otf
    - family: MAJALLAB
      fonts:
        - asset: assets/fonts/majalla.ttf
    - family: STENCIL
      fonts:
        - asset: assets/fonts/STENCIL.TTF
 
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
